### ISSUE TITLE
Create `dev` branch for branch protection of `main`

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#167]
### Description

The request for branch protection for [compliant-financial-infrastructure](https://github.com/finos/compliant-financial-infrastructure/) and [open-compliance-cdmc](https://github.com/finos/open-compliance-cdmc) was raised by @eddie-knight in the [#compliant-financial-infrastructure](https://finos-lf.slack.com/archives/C01RNUMC2DP) FINOS Slack channel.

- https://finos-lf.slack.com/archives/C01RNUMC2DP/p1636723813081500?thread_ts=1636465709.079500&cid=C01RNUMC2DP

### Tasks
- [ ] Inform compliant-financial-infrastructure community of intentions and allow to raise concerns before invoking next actions.
- On the [compliant-financial-infrastructure](https://github.com/finos/compliant-financial-infrastructure/) repo
  - [ ] Create `dev` branch and configure GitHub to enable branch protection of `main`.
- On the [open-compliance-cdmc](https://github.com/finos/open-compliance-cdmc) repo
  - [x] Create `dev` branch and configure GitHub to enable branch protection of `main`.
- [ ] Inform compliant-financial-infrastructure community of change.

**Comment by mcleo-d** [comment]
Hi @maoo - We're happy to move forward with the change for CFI. Thanks!

**Comment by maoo** [comment]
@mcleo-d - I've created a dev branch, see https://github.com/finos/compliant-financial-infrastructure/tree/dev , and enabled branch protection on `main`.

Please let me know if this is what you expected.

**Comment by mcleo-d** [comment]
Thank you @maoo - I'll let the maintainers know and will update the CFI team on Friday's call - #188

👏🏻 💯

**Comment by thinkl33t** [comment]
Thanks!

**Comment by eddie-knight** [comment]
We'll need to make sure we get an updated development workflow added to the contributor guidelines if that hasn't happened already :shipit: :+1:

**Comment by mcleo-d** [comment]
> We'll need to make sure we get an updated development workflow added to the contributor guidelines if that hasn't happened already :shipit: 👍

Thanks @eddie-knight - I've added to the CFI agenda - #188
