### ISSUE TITLE
Create `eks-legend` for Legend Deployment and Integration

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#212]
_Work in Progress_

## Description
Using the [legend-integration-helm](https://github.com/finos/legend-integration-helm/tree/main/charts/legend/1.0.0) repo as reference material, work with @maoo, @robmoffat and @TheJuanAndOnly99 at FINOS to adapt [CFI EKS](https://github.com/finos/compliant-financial-infrastructure/tree/dev/accelerators/kubernetes/eks) for [Legend](https://github.com/finos/legend).  

### Tasks

- [ ] Understand https://github.com/finos/legend-integration-helm/tree/main/charts/legend/1.0.0
- [ ] Schedule meeting with @maoo, @robmoffat and @TheJuanAndOnly99 to further groom _this_ issue
- [ ] Create `eks-legend` folder in `https://github.com/finos/compliant-financial-infrastructure/tree/dev/accelerators/kubernetes` _(see diagram below)_ 
- [ ] Create FINOS `repo` for `eks-legend` _(see diagram below)_ 
- [ ] Create FINOS `repo` for `EKS-legend-Tests` _(see diagram below)_
- [ ] Create adapted `Legend` automated `probr` tests and reporting

### Repo Organisation Diagram

![CFI Repo Organization](https://user-images.githubusercontent.com/21176439/157146521-9183b694-8c96-41b3-bae6-9740fbfefb74.png)

**Comment by eddie-knight** [comment]
This should be refined further by the Reproducible Infrastructure Working Group
