### ISSUE TITLE
Define the Service Approval Accelerator for Blob Storage on Microsoft Azure

### ISSUE THREAD

**Issue by peterrhysthomas** [finos/compliant-financial-infrastructure#40]
### Description:
Define the Service Approval Accelerator for Blob Storage using the[ Service Approval Accelerator Template](https://github.com/finos/cloud-service-certification/blob/master/templates/ServiceApprovalAcceleratorTemplate.md) for reference.

### Tasks:

- [ ] Create an azure\blob folder structure in the Cloud Services Certification project root.
- [ ] Define the Service Approval Accelerator for Blob Storage as markdown.
- [ ]  Commit Service Approval Accelerator for Blob Storage to azure\blob folder .
- [ ]  Raise PR to project team for review and merge.

**Comment by inhifistereo** [comment]
Would it be alright if the structure was azure/storage/blob? From there you'd see things like azure/storage/files, azure/storage/queues, etc. This is a much more familiar for those who use Azure rather than breaking out Azure Storage's resource types into their own feature. Thoughts?

**Comment by peterrhysthomas** [comment]
That sounds a good idea. But that would mean we should restructure everything to follow this convention. I think this needs a wider agreement, @mcleo-d can you add this to the next meeting’s agenda?
