### ISSUE TITLE
EPIC - Kubernetes Services

### ISSUE THREAD

**Issue by peterrhysthomas** [finos/compliant-financial-infrastructure#64]
###  Service Accelerator Templates
- [x] GCP GKE Service Accelerator Template (#65) - @alfredtommy
- [x] AWS EKS Service Accelerator Template (#66) - @abdullahgarcia 
- [ ] Azure AKS Service Accelerator Template (#67) - @tmewett && @TLATER
- [ ] OpenShift Service Accelerator Template (#92) - @J0EG 

### Infrastructure as Code
- [x] GCP GKE IaC (#65) - @alfredtommy

###  BDD Tests and Future 'Tests First' Initiatives
- [ ] Functional and Declarative BDD Testing Examples finos/compliant-financial-infrastructure#62, finos/compliant-financial-infrastructure#84, finos/compliant-financial-infrastructure#91 - @leefaus && @eddie-knight

**Comment by mcleo-d** [comment]
@peterrhysthomas - I have checked off `GCP GKE definition (#65) - @alfredtommy` in the anticipation of #65 being done now PR #73 is merged.

**Comment by eddie-knight** [comment]
Closing this issue as stale. The intent and subsequent work have been captured within the Reproducible Build Working Group.
