### ISSUE TITLE
Azure AKS definition

### ISSUE THREAD

**Issue by peterrhysthomas** [finos/compliant-financial-infrastructure#67]
## Completed Issues and Merged Pull Requests

- _add once complete_

## Current Work Items
- [x] Define the Service Approval Accelerator for Kubernetes on Azure #68 - @tmewett and @TLATER
- [ ] Create scripts for deployment of Kubernetes on Azure cluster as defined in Service Approval Accelerator template - @eddie-knight and @TLATER 
- [ ] Testing and validation of above mentioned scripts
- [ ] Raise PR request accordingly

**Comment by njwilliams** [comment]
happy to contribute to this!

**Comment by mcleo-d** [comment]
Hi @TLATER

I thought I'd introduce you to this epic Azure AKS definition #67 as it directly relates to the work being done in issue #67 and PR #72.

Kind regards,

James.

**Comment by mcleo-d** [comment]
Hi @TLATER - Are you happy to give an update on https://github.com/finos/cloud-service-certification/issues/67#issuecomment-740685096 at the next CSC meeting on 14th January and be added to the #89 agenda?

Speak soon,

James.

**Comment by TLATER** [comment]
Hi @mcleo-d - I'll miss that meeting unfortunately, but I'm planning to have another MR for this ready for review tomorrow (with the comments from the other one addressed).

Adam (can't find his github account for a ping) should be joining the meeting, though, I'll pass him my notes.
