### ISSUE TITLE
19 November 2020 - Cloud Service Certification Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#79]
## Date
Thursday 19 November 2020 - 10am EST / 3pm GMT

## Untracked attendees
| Name | Firm | Comment |
|:---------|:------------|:-----|

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes - https://github.com/finos/cloud-service-certification/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [x] Cloud Service Certification [Project Kanban](https://github.com/orgs/finos/projects/1) Review
- [x] @eddie-knight to form an opinion and report the viability of Pulumi and BDD Tests #62 including @leefaus & @alfredtommy
- [ ] **Portable Applications Across the Cloud** and **Governing Regulation Policy** with @alexmolev, @natishalom and [Cloudify](https://cloudify.co/) 
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made

- [x] @adamj-codethink update: @tmewett is unable to work on CSC for the time being and has introduced Tristan to the group. Welcome Tristan and thank you @tmewett for the work you've done and we hope to see you soon 😀 👍 
- [x] @adamj-codethink to ask @tmewett on whether @alfredtommy's feedback was incorporated into #72 and update the comments appropriately. @alfredtommy's feedback is found here ... https://github.com/finos/cloud-service-certification/pull/72#pullrequestreview-514376539 

## Action Items
- [x] @mcleo-d to arrange a PR review of #76 with @abdullahgarcia and the CSC group. This is confirmed for **Monday 30th November @11am ET / 4pm GMT** on the [FINOS Community WebEx](https://finos.webex.com/meet/community). All are invited to join.
- [x] @mcleo-d to arrange a CIS benchmarks and BDD meeting following a CSC project meeting discussion. See CSC issue #84 for updates. Meeting scheduled for **Wednesday 25th November @11:30am ET / 4:30pm GMT** on the [FINOS Community WebEx](https://finos.webex.com/meet/community). All are invited to join. 
- [x] @leefaus to rename #62 to `Functional versus Declarative BDD Testing Examples` and produce examples of Functional versus Declarative BDD Testing to share with the CSC project for wider input and feedback.

### WebEx info
**Webex:** 
https://finos.webex.com/finos/j.php?MTID=me0b8e6061812f875505b0caaceac3321

**Dial-in**
**US** +1-415-655-0003 US Toll
**UK** +44-20319-88141 UK Toll
**Access code:** 662 732 581

**Github Repo:** https://github.com/finos/cloud-service-certification/
**Project Wiki Page:** https://finosfoundation.atlassian.net/wiki/spaces/FDX/pages/904626436/Cloud+Service+Certification+Project

**Comment by abdullahgarcia** [comment]
Looks good James.

**Comment by leefaus** [comment]
here!  good to be back after some intense project completions.

**Comment by abdullahgarcia** [comment]
¡Hola!

**Comment by jamilmina1** [comment]
hi

**Comment by J0EG** [comment]
Good Morning/Afternoon/evening

**Comment by eddie-knight** [comment]
👋 :shipit:

**Comment by mcleo-d** [comment]
Hello! 👋

**Comment by danizheleva** [comment]
Hey @mcleo-d can you please share webex link, the one in the description is to a different room

**Comment by fleadsom** [comment]
Hey 👍

**Comment by adamj-codethink** [comment]
Hey o/

**Comment by peterrhysthomas** [comment]
> Hey @mcleo-d can you please share webex link, the one in the description is to a different room

https://finos.webex.com/webappng/sites/finos/meeting/download/c52b960ab5234f4c85a66a7fd9ce83bc_20201119T150000Z?MTID=m4b1d85127d1f3ca179545d6bd3291975&launchApp=true

**Comment by mcleo-d** [comment]
Link shared by @abdullahgarcia in the meeting ...

https://www.eksworkshop.com/intermediate/300_cis_eks_benchmark/ssh-into-node/

> @abdullahgarcia - "In this link it highlights how kube-bench is running CIS Benchmarks against the worker nodes."

**Comment by admiyo** [comment]
Good Morning and Hello!

**Comment by mcleo-d** [comment]
Hey @peterrhysthomas,

Pull request #83 brings the meeting link below in line with the CSC meeting link in the [FINOS project calendar](https://calendar.google.com/calendar/u/0/embed?src=finos.org_fac8mo1rfc6ehscg0d80fi8jig@group.calendar.google.com&ctz=America/New_York).

Please feel free to review, feedback and merge 👍 

James.

> > Hey @mcleo-d can you please share webex link, the one in the description is to a different room
> 
> https://finos.webex.com/webappng/sites/finos/meeting/download/c52b960ab5234f4c85a66a7fd9ce83bc_20201119T150000Z?MTID=m4b1d85127d1f3ca179545d6bd3291975&launchApp=true
