### ISSUE TITLE
EPIC - PostgreSQL

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#80]
###  Service Accelerator Templates 

- [ ] GCP PostgreSQL Service Accelerator Definition ( )
- [ ] AWS PostgreSQL Service Accelerator Definition ( )
- [x] Azure PostgreSQL Service Accelerator Definition (#60) - @danizheleva 

###  BDD Tests First

- [ ] GCP PostgreSQL BDD ( )
- [ ] AWS PostgreSQL BDD ( ) 
- [ ] Azure PostgreSQL BDD ( ) - @peterrhysthomas && @danizheleva && @fleadsom

### Infrastructure as Code

- [ ] GCP PostgreSQL IaC ( )
- [ ] AWS PostgreSQL IaC ( ) 
- [ ] Azure PostgreSQL IaC (#98) - @peterrhysthomas && @danizheleva && @fleadsom
