### ISSUE TITLE
OpenShift Kubernetes Definition

### ISSUE THREAD

**Issue by mcleo-d** [finos/compliant-financial-infrastructure#92]
## Work Items
- [x] Service Accelerator Template for OpenShift (Kubernetes) 
  - https://github.com/finos/compliant-financial-infrastructure/pull/170
  - https://github.com/finos/compliant-financial-infrastructure/pull/205
- [ ] Create scripts for deployment as defined in [Service Approval Accelerator template](https://github.com/finos/compliant-financial-infrastructure/tree/dev/accelerators/kubernetes/ocp)
  - [x] https://github.com/finos/compliant-financial-infrastructure/issues/201
- [ ] Testing and validation of above mentioned scripts
- [ ] Raise PR request accordingly

**Comment by mcleo-d** [comment]
@leefaus and @J0EG 👋🏻 

Thanks for your feedback regarding noting closed PR #97 on this issue. I have updated above for your information ... 

- https://github.com/finos/cloud-service-certification/issues/92#issue-791966523

James 🚀

**Comment by mcleo-d** [comment]
@J0EG - Async review and possible offline session required to review new PR.

- [ ] @J0EG to organise async review via Slack and other GitHub channels (GH issue, PR etc)
- [ ] If needed, @mcleo-d to organise Zoom call and open to the CSC project for week commencing 19th July.

Note : Async is the preferred approach due to getting people together and into an organised call.

**Comment by AdrianHammond** [comment]
@mcleo-d I just noticed that the link to the in the second task above "Create scripts for deployment as defined in" is broken, I can raise a PR but before doing so I wanted to double check which accerator doc you were linking to, I assume this one [](https://github.com/finos/compliant-financial-infrastructure/blob/dev/accelerators/kubernetes/ocp/sat_rh_ocp.adoc). Thanks

**Comment by mcleo-d** [comment]
Hi @AdrianHammond,

Thanks for raising the broken link. The project structure update made by @eddie-knight and @thinkl33t in #200 created the 404, so I have simply updated the link to the newly created [ocp](https://github.com/finos/compliant-financial-infrastructure/tree/dev/accelerators/kubernetes/ocp) folder.

I hope this works for you?

James.

**Comment by AdrianHammond** [comment]
forked /dev branch to https://github.com/AdrianHammond/compliant-financial-infrastructure

**Comment by AdrianHammond** [comment]
Hi @mcleo-d 

I think it might be possible to close this off as with the work already done with merge #235 and the following new issues

1. #253 to create IAC for OCP on GCP has been superseded by #201
2. #229 Updating OCP SAA to new template


I think the open actions in this issue are now redundant. What do you think?

Thanks Adrian

**Comment by AdrianHammond** [comment]
@mcleo-d this can be closed as superceeded by #253 and #229

**Comment by eddie-knight** [comment]
My bad, I went on a duplicate-creating spree a while back
